# Generated by Django 3.1.7 on 2021-07-06 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artphoto', models.ImageField(blank=True, upload_to=None)),
                ('price', models.FloatField(null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Sold', 'Sold')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('Paper', 'Paper'), ('Canvas', 'Canvas'), ('Wood', 'Wood'), ('Leather', 'Leather'), ('Plastic', 'Plastic'), ('Yarn', 'Yarn'), ('Glass', 'Glass'), ('Clay', 'Clay'), ('Metal', 'Metal'), ('Fabric', 'Fabric'), ('Beads', 'Beads'), ('Other', 'Other')], max_length=200, null=True)),
                ('atype', models.CharField(choices=[('Drawing', 'Drawing'), ('Painting', 'Painting'), ('Sculpture', 'Sculpture'), ('Tapestry', 'Tapestry'), ('Ceramic', 'Ceramic'), ('Weaving', 'Weaving'), ('Beadwork', 'Beadwork'), ('Other', 'Other')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, null=True)),
                ('lname', models.CharField(max_length=50, null=True)),
                ('phonenumber', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('custprof', models.ImageField(blank=True, upload_to=None)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], max_length=100, null=True)),
                ('date', models.DateField()),
                ('art', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arts.art')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, null=True)),
                ('lname', models.CharField(max_length=50, null=True)),
                ('phonenumber', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('artprof', models.ImageField(blank=True, upload_to=None)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='art',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arts.artist'),
        ),
        migrations.AddField(
            model_name='art',
            name='category',
            field=models.ManyToManyField(to='arts.Category'),
        ),
    ]
