# Generated by Django 3.1.7 on 2021-07-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0002_auto_20210706_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='artphoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artprof',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='custprof',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
