# Generated by Django 3.1.7 on 2021-07-08 18:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arts', '0004_auto_20210708_1129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist',
            new_name='ArtistProfile',
        ),
    ]
