# Generated by Django 3.1.7 on 2021-07-11 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0005_auto_20210708_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_type', models.CharField(choices=[('Drawing', 'Drawing'), ('Painting', 'Painting'), ('Sculpture', 'Sculpture'), ('Tapestry', 'Tapestry'), ('Ceramic', 'Ceramic'), ('Weaving', 'Weaving'), ('Beadwork', 'Beadwork'), ('Mosaic', 'Mosaic'), ('Collage', 'Collage'), ('Other', 'Other')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(choices=[('Paper', 'Paper'), ('Canvas', 'Canvas'), ('Wood', 'Wood'), ('Leather', 'Leather'), ('Plastic', 'Plastic'), ('Yarn', 'Yarn'), ('Glass', 'Glass'), ('Clay', 'Clay'), ('Metal', 'Metal'), ('Fabric', 'Fabric'), ('Beads', 'Beads'), ('Mixed-Media', 'Mixed-Media'), ('Other', 'Other')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], max_length=50, null=True)),
                ('method', models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('M-Pesa', 'M-Pesa')], max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='art',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='bio',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arts.artistprofile'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arts.order'),
        ),
        migrations.AddField(
            model_name='art',
            name='arttype',
            field=models.ManyToManyField(to='arts.ArtType'),
        ),
        migrations.AddField(
            model_name='art',
            name='material',
            field=models.ManyToManyField(to='arts.Material'),
        ),
    ]
