# Generated by Django 3.1.7 on 2021-07-16 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0008_auto_20210716_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='artist',
        ),
    ]
