# Generated by Django 3.1.7 on 2021-07-18 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0010_auto_20210718_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
