# Generated by Django 3.1.7 on 2021-07-18 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0012_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arts.artistprofile'),
        ),
    ]
