# Generated by Django 3.1.7 on 2021-07-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0013_art_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='arttype',
        ),
        migrations.AddField(
            model_name='art',
            name='art_type',
            field=models.CharField(choices=[('Drawing', 'Drawing'), ('Painting', 'Painting'), ('Sculpture', 'Sculpture'), ('Tapestry', 'Tapestry'), ('Ceramic', 'Ceramic'), ('Weaving', 'Weaving'), ('Beadwork', 'Beadwork'), ('Mosaic', 'Mosaic'), ('Collage', 'Collage'), ('Other', 'Other')], max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='art',
            name='material',
        ),
        migrations.AddField(
            model_name='art',
            name='material',
            field=models.CharField(choices=[('Paper', 'Paper'), ('Canvas', 'Canvas'), ('Wood', 'Wood'), ('Leather', 'Leather'), ('Plastic', 'Plastic'), ('Yarn', 'Yarn'), ('Glass', 'Glass'), ('Clay', 'Clay'), ('Metal', 'Metal'), ('Fabric', 'Fabric'), ('Beads', 'Beads'), ('Mixed-Media', 'Mixed-Media'), ('Other', 'Other')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='ArtType',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
