# Generated by Django 3.1.7 on 2021-08-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0018_auto_20210811_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='payment',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete')], max_length=200, null=True),
        ),
    ]
