# Generated by Django 3.1.7 on 2021-08-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0019_delivery_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='payment',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=200, null=True),
        ),
    ]
