# Generated by Django 3.1.7 on 2021-08-24 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0024_remove_art_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
